### ISSUE TITLE
如何特征库的制作

### ISSUE THREAD

**Issue by clickear** [aiden2048/Rotate-Captcha-Angle-Prediction#1]
<del>这里的特征库，是用标记好的，旋转正确角度的图片提出出特征库吗？
原理就是，通过图片特征与 提前做好的正确角度的特征值做比对？</del>
那就是每次用之前，要先标记好，旋转正确的图片库？

**Comment by decodecaptcha** [comment]
没错, 你已经看懂了, 说明1.1, 这里你需要知道图片的正确角度, 部分网站会返回响应正确角度, 若没有只能自己手动找角度, 使用工具 restoration.py  进行批量矫正或手动矫正
